"""add_study_group_topic_and_student_class

Revision ID: eb4d8cfb75bb
Revises: 5f6dd178f674
Create Date: 2026-04-19 15:57:31.770491

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'eb4d8cfb75bb'
down_revision: Union[str, None] = '5f6dd178f674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_groups', sa.Column('topic', sa.String(length=255), nullable=True))
    op.add_column('study_groups', sa.Column('student_class', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('study_groups', 'student_class')
    op.drop_column('study_groups', 'topic')
    # ### end Alembic commands ###
